using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class startTrigger : MonoBehaviour
{
    private tetrominoSpawnManager TetrominoSpawnManager;
    private bool gameStarted = false;
    
    // Start is called before the first frame update
    void Start()
    {
        TetrominoSpawnManager = FindObjectOfType<tetrominoSpawnManager>();
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.gameObject.tag == "Player" && !gameStarted)
        {
            GetComponent<AudioSource>().Play();
            TetrominoSpawnManager.spawnTetromino();
            gameStarted = true;
        }
    }
}
